SCALE = 0.6
ZOOM = 1.6
MAP_SCALE = 5 * ZOOM * SCALE

DEFAULT_FPS = 60

WINDOW_WIDTH = 1920 * SCALE
WINDOW_HEIGHT = 1080 * SCALE
WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)

PLAYER_WIDTH = 80 * SCALE * ZOOM
PLAYER_HEIGHT = 80 * SCALE * ZOOM
PLAYER_SIZE = (PLAYER_WIDTH, PLAYER_HEIGHT)

PLAYER_SPEED = 6 * SCALE * ZOOM
PLAYER_DASH = 40 * SCALE * ZOOM
PLAYER_ATTACK_RANGE = 20 * SCALE * ZOOM
PLAYER_RUN_DELAY = 3
PLAYER_IDLE_DELAY = 5
PLAYER_ATTACK_DELAY = 5

ENEMY_WIDTH = 70 * SCALE * ZOOM
ENEMY_HEIGHT = 70 * SCALE * ZOOM
ENEMY_SIZE = (ENEMY_WIDTH, ENEMY_HEIGHT)
ENEMY_SPEED = 3 * SCALE * ZOOM
ENEMY_DELAY = 10
ENEMY_ATTACKING_DELAY = 8


# Player Stats

PLAYER_BASE_HP = 100
PLAYER_BASE_MANA = 100
PLAYER_BASE_DAMAGE = 20

PLAYER_GROWTH_HP = 24
PLAYER_GROWTH_MANA = 15
PLAYER_GROWTH_DAMAGE = 10

PLAYER_ATTACK_CD = 10
PLAYER_DASH_CD = 40

