SCALE = 0.6

DEFAULT_FPS = 60

WINDOW_WIDTH = 1920 * SCALE
WINDOW_HEIGHT = 1080 * SCALE
WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)

PLAYER_WIDTH = 80 * SCALE
PLAYER_HEIGHT = 80 * SCALE
PLAYER_SIZE = (PLAYER_WIDTH, PLAYER_HEIGHT)

PLAYER_SPEED = 2

ENEMY_WIDTH = 40 * SCALE
ENEMY_HEIGHT = 80 * SCALE
ENEMY_SIZE = (ENEMY_WIDTH, ENEMY_HEIGHT)

PLAYER_SPEED = 4
PLAYER_RUN_DELAY = 2
PLAYER_IDLE_DELAY = 5

# Player Stats

PLAYER_BASE_HP = 100
PLAYER_BASE_MANA = 100
PLAYER_BASE_DAMAGE = 20

PLAYER_GROWTH_HP = 24
PLAYER_GROWTH_MANA = 15
PLAYER_GROWTH_DAMAGE = 10

